### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by bbarthel** [aws-samples/ask-around-me#4]
When I try viewing the production site, I get the following error:

![image](https://user-images.githubusercontent.com/4349780/84933102-faf47b80-b09a-11ea-8c75-59c4d4f63b1f.png)

I have tried using my local code that works and commited to CodeCommit and also using Github.  Any ideas/suggestions?

**Comment by jbesw** [comment]
I would recommend checking https://community.auth0.com/t/redirect-too-many-times/35606/9 and verifying the callback URLs are all exactly correct (check trailing slashes, etc.) Auth0 handles the redirects between the auth and the app, so it's difficult to debug.

**Comment by bbarthel** [comment]
What should be the build settings be in amplify.yml?  This is what mine look like:

version: 1
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []

**Comment by jbesw** [comment]
Mine looks like this:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
